### ISSUE TITLE
Odds Line Not Switching to State from Drop Down

### ISSUE THREAD

**Issue by ohwowmarketing** [ohwowmarketing/acmx-sgg#14]
If you follow this flow.

Home Page > NFL Betting Lines Image > Odds Lines
Select State from drop down
Odds lines are not switching to the selected state and not updating to the wildcard schedule.

**Comment by moseley** [comment]
According to the Sports Data IO API documentation for retrieving the current week, "Week number is an integer between 1 and 21 or the word current. Weeks 1 through 17 are regular season weeks. Weeks 18 through 21 are post-season weeks." However, the API call is currently returning the number 1.
